version: '3'

networks:
  backend:

services:

  unicorn:
    build: .
      # context: .
      # dockerfile: Dockerfile
    # command: ["flask", "run", "--host=0.0.0.0"]
    depends_on:
      - cluster-db
      # - social-db
    environment:
      - IMAGE_LIMIT=4000
    ports:
      - 5000:5000
    networks:
      - backend
    volumes:
      - .:/app
    env_file:
      - unicorn.env

  cluster-db:
    image: newknowledge.azurecr.io/ds/cluster-db-dev:seed-dev
    environment:
      - POSTGRES_USER=cluster
    networks:
      - backend

  social-db:
    image: newknowledge.azurecr.io/ds/social-db-dev:seed-dev
    environment:
      - POSTGRES_USER=social
    networks:
      - backend
