version: '3'

networks:
  backend:

services:

  unicorn:
    build:
      context: .
      dockerfile: http.slim.dockerfile
    
    command: ["flask", "run", "--host=0.0.0.0"]
    depends_on:
      - cluster-db
      - social-db
    env_file:
      - unicorn.env
    environment:
      - FLASK_ENV=development
    ports: 
      - 5000:5000
    networks:
      - backend
    volumes:
      - .:/app

  cluster-db:
    image: newknowledge.azurecr.io/ds/cluster-db-dev:seed-latest
    environment:
      - POSTGRES_USER=cluster
    networks:
      - backend

  social-db:
    image: newknowledge.azurecr.io/ds/social-db-dev:seed-dev
    environment:
      - POSTGRES_USER=social
    networks:
      - backend